name: FunctionalMenu
version: '${project.version}'
main: com.g4vrk.functionalMenu.test.FunctionalMenuPlugin
api-version: '1.16'
authors: [ g4vrk ]
website: https://github.com/g4vrk/FunctionalMenu
softdepend:
  - packetevents

commands:
  testmenu: {}